{% set name = "pathfinder2e-stats" %}
{% set version = "0.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pathfinder2e_stats-{{ version }}.tar.gz
  sha256: 9e9d7e27c4bdc8a9bceac80b68269fd261922c248f66959d53ab5424c21403d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=66
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - pandas >=2.1
    - xarray >=2024.10.0

test:
  imports:
    - pathfinder2e_stats
  commands:
    # Test that resource files are accessible
    - python -c "import pathfinder2e_stats as pf2; print(pf2.tables.DC)"
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/crusaderky/pathfinder2e_stats
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Statistical tools for Pathfinder 2nd edition'

extra:
  recipe-maintainers:
    - crusaderky
